ALTER TABLE posts ADD COLUMN slug TEXT;
ALTER TABLE posts ADD COLUMN description TEXT;
ALTER TABLE posts ADD COLUMN pub_date TEXT;
ALTER TABLE posts ADD COLUMN category TEXT;
ALTER TABLE posts ADD COLUMN tags TEXT;
ALTER TABLE posts ADD COLUMN featured INTEGER NOT NULL DEFAULT 0;

ALTER TABLE sns_drafts ADD COLUMN topic TEXT;
ALTER TABLE sns_drafts ADD COLUMN goal TEXT;
ALTER TABLE sns_drafts ADD COLUMN tone TEXT;
ALTER TABLE sns_drafts ADD COLUMN caption TEXT;
ALTER TABLE sns_drafts ADD COLUMN slides_json TEXT;

CREATE TABLE IF NOT EXISTS analytics_summaries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  period TEXT NOT NULL,
  visits INTEGER NOT NULL DEFAULT 0,
  readings INTEGER NOT NULL DEFAULT 0,
  chat_starts INTEGER NOT NULL DEFAULT 0,
  note_views INTEGER NOT NULL DEFAULT 0,
  next_action TEXT NOT NULL,
  memo TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
